import assert from "node:assert/strict";import test from "node:test";import{HttpSourceAcquirer}from "../src/orchestrator/http-source-acquirer.ts";import{EvidenceResearchCapability}from "../src/orchestrator/evidence-research-capability.ts";import type{WorkAction}from "../src/orchestrator/work-capability.ts";
function action(claims:unknown[]):WorkAction{return{goalId:"g",jobId:"j",attemptId:"a",strategyId:"s",capability:"research.evidence",domain:"research",operation:"verify-claims",input:{claims},scope:[],expectedOutputs:[],risk:"low",access:"read",externalSideEffect:false,irreversible:false,verifier:{kind:"fact",required:true,spec:{}}}}
const acquirer=(bodies:Record<string,string>)=>new HttpSourceAcquirer({fetchImpl:async(input)=>new Response(bodies[String(input)]??"{}",{headers:{"content-type":"application/json"}}),now:()=>new Date("2026-09-22T00:00:00Z"),classify:()=> "official"});
test("research capability confirms claim only from acquired source evidence",async()=>{const cap=new EvidenceResearchCapability(acquirer({"https://example.go.jp/facts":"{\"amount\":42}"}));const r=await cap.execute(action([{id:"amount",value:42,required:true,sourceUrls:["https://example.go.jp/facts"]}]));assert.equal(r.ok,true);assert.equal((r.outputs.claims as Array<{status:string}>)[0].status,"CONFIRMED");assert.match(String((r.evidence[0]?.data as {sha256?:unknown})?.sha256),/^[a-f0-9]{64}$/)});
test("research capability blocks unsupported and conflicting claims",async()=>{const cap=new EvidenceResearchCapability(acquirer({"https://a.go.jp/f":"{\"amount\":42}","https://b.go.jp/f":"{\"amount\":24}"}));const conflict=await cap.execute(action([{id:"amount",value:42,required:true,sourceUrls:["https://a.go.jp/f","https://b.go.jp/f"]}]));assert.equal(conflict.ok,false);assert.deepEqual(conflict.outputs.blocked,["amount"]);const missing=await cap.execute(action([{id:"amount",value:42,required:true,sourceUrls:[]}]));assert.equal(missing.ok,false);assert.deepEqual(missing.outputs.blocked,["amount"])});

test("local-only mode accepts verified local evidence without web",async()=>{const cap=new EvidenceResearchCapability(acquirer({}));const r=await cap.execute(action([{id:"amount",value:42,required:true,evidencePolicy:"LOCAL_EVIDENCE_SUFFICIENT",localSources:[{id:"file:rules.xlsx",sourceClass:"primary_original",retrievedAt:"2026-09-22T00:00:00Z",value:42}]}]));assert.equal(r.ok,true);assert.equal((r.outputs.claims as Array<{status:string}>)[0].status,"CONFIRMED");assert.equal(r.evidence.length,0)});
test("inference allowed stays INFERRED and does not masquerade as confirmed",async()=>{const cap=new EvidenceResearchCapability(acquirer({}));const r=await cap.execute(action([{id:"idea",value:"possible",required:true,evidencePolicy:"INFERENCE_ALLOWED"}]));assert.equal(r.ok,true);assert.equal((r.outputs.claims as Array<{status:string}>)[0].status,"INFERRED")});
test("fact-not-applicable work needs no factual evidence",async()=>{const cap=new EvidenceResearchCapability(acquirer({}));const r=await cap.execute(action([{id:"rewrite",value:"clearer",required:true,evidencePolicy:"FACT_NOT_APPLICABLE"}]));assert.equal(r.ok,true);assert.deepEqual(r.outputs.claims,[])});
