import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp,mkdir,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CompassStore } from "../src/compass/store.ts";
import { CognitiveService } from "../src/gai/cognitive-service.ts";
import { GoalControllerRuntime } from "../src/orchestrator/goal-controller-runtime.ts";
import { CompassGoalRegistryAdapter } from "../src/orchestrator/compass-goal-controller.ts";
import { acquireCognitiveLease } from "../src/gai/cognitive-lease.ts";
async function fixture(){const root=await mkdtemp(join(tmpdir(),"goriq-dod-")),db=join(root,"compass.db"),data=join(root,"data");await mkdir(data);const compass=new CompassStore(db);await new GoalControllerRuntime({registry:new CompassGoalRegistryAdapter(compass)}).handle({source:"jarvis",text:"添付文書をそのまま保存して完成させて"});const goal=compass.getGoal()!;compass.close();const service=new CognitiveService(db,{materialIntake:{dataRoot:data}}),status=await service.status();return{root,db,data,goal,service,status,input:{goalId:status.goalId,goalDigest:status.goalDigest,successCriteria:["添付内容を保持したファイルを取得できる"],acknowledgement:true}};}
test("normal Goal intake gains explicit DoD, keeps identity and completes material work after verified download",async()=>{const f=await fixture();try{assert.deepEqual(f.goal.successCriteria,[]);assert.equal(f.status.goalRefinementAvailable,true);await f.service.refineGoal(f.input);const next=await f.service.status();assert.equal(next.goalId,f.status.goalId);assert.notEqual(next.goalDigest,f.status.goalDigest);assert.equal(next.goalComplete,false);assert.equal(next.goalRefinementAvailable,false);assert.equal(next.attempts,0);const restarted=new CognitiveService(f.db,{materialIntake:{dataRoot:f.data}});const replay=await restarted.refineGoal(f.input);assert.equal(replay.replayed,true);await restarted.prepareMaterials({goalId:next.goalId,goalDigest:next.goalDigest,materials:[{format:"text",content:"42",criteria:["criterion-1"]}],mappingAcknowledged:true});assert.equal((await restarted.continue(next.goalId!)).stopReason,"goal_complete");assert.equal((await restarted.output(next.goalId!,"output-1")).bytes.toString(),"42");assert.equal((await restarted.status()).metrics.externalAiCallsPerGoal,0);assert.equal((await restarted.refineGoal(f.input)).replayed,true);}finally{await rm(f.root,{recursive:true,force:true});}});
test("Goal refinement rejects scope injection, stale request, existing cognition and concurrent lease",async()=>{const f=await fixture();try{for(const bad of [{...f.input,goalDigest:"0".repeat(64)},{...f.input,acknowledgement:false},{...f.input,title:"replacement"},{...f.input,successCriteria:["password=must-not-enter-memory"]}])await assert.rejects(()=>f.service.refineGoal(bad));const release=await acquireCognitiveLease(f.db+".cognitive-run.lock");try{await assert.rejects(()=>f.service.refineGoal(f.input));}finally{await release();}await f.service.continue(f.status.goalId!);await assert.rejects(()=>f.service.refineGoal(f.input),/existing|pristine|review/i);const c=new CompassStore(f.db);assert.deepEqual(c.getGoal(),f.goal);c.close();}finally{await rm(f.root,{recursive:true,force:true});}});
