import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,mkdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {CompassStore} from "../src/compass/store.ts";
import {CognitiveService} from "../src/gai/cognitive-service.ts";
import type {PrimaryBrainAdapter, PrimaryBrainContext} from "../src/gai/primary-brain.ts";

const decision=()=>({candidateId:null,plan:[],assessment:"Local draft",hypotheses:[],expectedOutcome:"Draft only",confidence:0.8,requiredEvidence:["Independent output readback"],recoveryOptions:[],escalation:"none" as const,goalDraft:{successCriteria:["The output preserves the supplied text"],assumptions:["Source text will be supplied"],unresolvedQuestions:[]}});
function brain(plan:(context:PrimaryBrainContext)=>Promise<unknown>):PrimaryBrainAdapter{return {id:"local-test",plan,infer:plan,classify:plan,summarize:plan,hypothesize:plan,critique:plan,estimateConfidence:async()=>0.8} as PrimaryBrainAdapter;}
async function fixture(t:{after(fn:()=>Promise<void>):void},adapter:PrimaryBrainAdapter){const root=await mkdtemp(join(tmpdir(),"goriq-draft-"));t.after(()=>rm(root,{recursive:true,force:true}));const dbPath=join(root,"compass.db"),dataRoot=join(root,"data");await mkdir(dataRoot);const db=new CompassStore(dbPath);db.setGoal({title:"Save supplied text",constraints:["Local only"]});db.close();const service=new CognitiveService(dbPath,{materialIntake:{dataRoot},brain:adapter});const state=await service.status();const read=()=>{const db=new CompassStore(dbPath);try{return{goal:db.getGoal(),state:db.getState()};}finally{db.close();}};return{dbPath,service,read,input:{goalId:state.goalId!,goalDigest:state.goalDigest!}};}
test("local DoD proposal is bounded unverified data and never changes Goal or executes",async t=>{let calls=0;const f=await fixture(t,brain(async c=>{calls++;assert.equal(c.purpose,"goal-draft");assert.equal(c.candidates.length,0);assert.equal(c.budget.remainingActions,0);assert.deepEqual(c.constraints,["Local only"]);return decision();}));const before=f.read();const result=await f.service.proposeGoalCriteria(f.input);assert.equal(calls,1);assert.equal(result.status,"PROPOSED");assert.equal(result.verification,"UNVERIFIED");assert.deepEqual(result.draft.successCriteria,decision().goalDraft.successCriteria);assert.notDeepEqual(result.draft.successCriteria,decision().requiredEvidence);assert.deepEqual(f.read(),before);assert.equal((await f.service.status()).attempts,0);await f.service.refineGoal({...f.input,successCriteria:result.draft.successCriteria,acknowledgement:true});assert.equal((await f.service.status()).goalComplete,false);});
test("proposal rejects existing work and stale Goal with zero model calls",async t=>{let calls=0;const f=await fixture(t,brain(async()=>{calls++;return decision();}));await assert.rejects(f.service.proposeGoalCriteria({...f.input,goalDigest:"0".repeat(64)}));await assert.rejects(f.service.proposeGoalCriteria({...f.input,permissions:["all"]}));assert.equal(calls,0);await f.service.refineGoal({...f.input,successCriteria:["Explicit outcome"],acknowledgement:true});await assert.rejects(f.service.proposeGoalCriteria(f.input));assert.equal(calls,0);});
test("Compass writes during inference invalidate a proposal without overwriting them",async t=>{let dbPath="";const f=await fixture(t,brain(async()=>{const db=new CompassStore(dbPath);db.updateState({active:["concurrent work"]});db.close();return decision();}));dbPath=f.dbPath;await assert.rejects(f.service.proposeGoalCriteria(f.input),/changed/i);assert.deepEqual(f.read().state.active,["concurrent work"]);assert.deepEqual(f.read().goal!.successCriteria,[]);});
test("invalid/unavailable local suggestions keep manual adoption available without retries",async t=>{for(const value of [null,{...decision(),goalDraft:undefined},{...decision(),goalDraft:{...decision().goalDraft,permissions:["all"]}},{...decision(),goalDraft:{...decision().goalDraft,successCriteria:["password=synthetic-rejected"]}}]){let calls=0;const f=await fixture(t,brain(async()=>{calls++;if(!value)throw Error("local unavailable");return value;}));const before=f.read();await assert.rejects(f.service.proposeGoalCriteria(f.input));assert.equal(calls,1);assert.deepEqual(f.read(),before);assert.equal((await f.service.status()).goalRefinementAvailable,true);await f.service.refineGoal({...f.input,successCriteria:["Owner supplied outcome"],acknowledgement:true});}});
