import test from 'node:test';
import assert from 'node:assert/strict';
import {JarvisTaskQueue} from '../src/jarvis/task-queue.ts';
import {prepareWorkerRemote} from '../src/jarvis/prepare-worker-remote.ts';
import {remoteDeviceInventory} from '../src/jarvis/remote-device-inventory.ts';
import type {JarvisNode,JarvisTask} from '../src/jarvis/types.ts';
const node:JarvisNode={id:'n',label:'fixture',kind:'android',status:'ready',capabilities:['remote-view','remote-control','wake-device'],policy:{allowRemoteControl:true,allowPaidServices:false,allowDestructiveActions:false,allowExternalPublication:false,requireHumanForLockedDevice:true},telemetry:{checkedAt:new Date().toISOString(),accessibilityEnabled:true,remoteProtocol:1,screenInteractive:false,locked:false},lastSeenAt:new Date().toISOString(),enrollment:'quick'};
test('screen off is visible independently of controllable capability',()=>{const d=remoteDeviceInventory([node],[])[0];assert.equal(d.remoteAssistCapability,'CONTROLLABLE');assert.match(d.reason,/画面OFF/);assert.equal(d.state,'sleeping');});
test('wake preparation waits for signed completion before allowing capture',async()=>{let time=0;const calls:string[]=[];let polls=0;const r=await prepareWorkerRemote(node,async(path)=>{calls.push(path);return Response.json(path.endsWith('/wake')?{task:{id:'t'}}:{fleet:[node],tasks:[{id:'t',status:++polls===2?'completed':'running'}]});},{now:()=>time,sleep:async ms=>{time+=ms;}});assert.equal(r,'wake-completed');assert.equal(polls,2);assert.equal(calls[0],'/api/jarvis/admin/remote/wake');});
test('wake failure and timeout never become success',async()=>{for(const status of ['failed','queued']){let time=0;await assert.rejects(prepareWorkerRemote(node,async p=>Response.json(p.endsWith('/wake')?{task:{id:'t'}}:{fleet:[node],tasks:[{id:'t',status}]}),{now:()=>time,sleep:async ms=>{time+=ms;}}));}});
test('offline/locked/permission denied never enqueue a wake',async()=>{for(const n of [{...node,lastSeenAt:'2000-01-01'},{...node,telemetry:{...node.telemetry,locked:true}},{...node,policy:{...node.policy,allowRemoteControl:false}}]){await assert.rejects(prepareWorkerRemote(n,async()=>{assert.fail('must not enqueue');}));}});
test('restored bounded wake cannot be claimed after expiry; ordinary tasks unaffected',()=>{const q=new JarvisTaskQueue();const now=new Date('2026-01-01T00:00:00Z');const t:JarvisTask={id:'w',idempotencyKey:'w',type:'wake-device',payload:{},status:'queued',requiredCapabilities:['wake-device'],priority:'high',requiresOnline:true,attempts:0,maxAttempts:1,createdAt:now.toISOString(),updatedAt:now.toISOString(),dispatchBefore:now.toISOString()};q.restore([t]);assert.equal(q.next(now),undefined);assert.equal(q.get('w')?.status,'cancelled');q.restore([{...t,status:'leased',assignedNodeId:'n'}]);assert.equal(q.assignedTo('n',now).length,0);q.restore([{...t,dispatchBefore:undefined}]);assert.equal(q.next(now)?.id,'w');});

test('revocation during wake prevents session creation',async()=>{let time=0;await assert.rejects(prepareWorkerRemote(node,async p=>Response.json(p.endsWith('/wake')?{task:{id:'t'}}:{fleet:[{...node,policy:{...node.policy,allowRemoteControl:false}}],tasks:[{id:'t',status:'completed'}]}),{now:()=>time,sleep:async ms=>{time+=ms;}}));});
