import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { TeachingStore, replayTeaching, selectVariant, safeUrl, profileKey, type DeviceProfile, type TeachingAdapter, type Observation } from "../src/jarvis/teaching.ts";
import { observeAndroidUi, demonstratedStep } from "../src/jarvis/teaching-observation.ts";
const device:DeviceProfile={deviceId:'d1',platform:'android',model:'Model-A',osVersion:'15',app:'com.example.app',appVersion:'1'};
const obs=(signature:string,p=device):Observation=>({signature,profile:p,targets:[],protectedScreen:false});
function fixture(){const root=mkdtempSync(join(tmpdir(),'teaching-'));const path=join(root,'memory.json');return {root,path,store:new TeachingStore(path),clean:()=>rmSync(root,{recursive:true,force:true})};}
function draft(store:TeachingStore,p=device,gate=false){const v=store.start({goal:'URL work',scope:'model',profile:p,sessionId:'session'});store.append(v.id,{action:{kind:'key',key:'HOME'},before:'a',after:'b',gate});store.finish(v.id,'result visible','b');return store.get(v.id);}
function adapter(p=device){let screen='a',calls=0;const driver:TeachingAdapter={authorize(){},async observe(){return obs(screen,p);},async execute(){calls++;screen='b';}};return {driver,calls:()=>calls,reset:()=>{screen='a';}};}
test('all five platform teaching records survive reload without claiming automatic verification',()=>{const f=fixture();try{for(const platform of ['android','ios','windows','macos','linux'] as const){const v=f.store.manual({goal:'URL work',scope:'device',profile:{...device,platform,deviceId:platform},instructions:'Open browser\nOpen the row URL',completion:'Result visible'});assert.equal(v.status,'DRAFT');assert(v.steps.every(s=>s.gate));}assert.equal(new TeachingStore(f.path).list().variants.length,5);}finally{f.clean();}});
test('specific-device variant wins and incompatible model/OS/app version is rejected',()=>{const f=fixture();try{const model=draft(f.store);const local=f.store.manual({goal:'URL work',scope:'device',profile:device,instructions:'local change',completion:'done'});assert.equal(selectVariant([model,local],'URL work',device)?.id,local.id);for(const patch of [{osVersion:'16'},{appVersion:'2'},{platform:'ios' as const},{model:'Other',deviceId:'d2'}])assert.equal(selectVariant([model],'URL work',{...device,...patch}),null);}finally{f.clean();}});
test('separate reproduction is mandatory, then execution works; another device must reverify',async()=>{const f=fixture();try{const v=draft(f.store);const a=adapter();await assert.rejects(replayTeaching(f.store,v.id,a.driver,'execute'),/Verify/);const r=await replayTeaching(f.store,v.id,a.driver,'verify');assert.equal(r.status,'PASSED');assert.equal(f.store.get(v.id).status,'VERIFIED');a.reset();assert.equal((await replayTeaching(f.store,v.id,a.driver,'execute')).status,'PASSED');assert.equal(a.calls(),2);await assert.rejects(replayTeaching(f.store,v.id,adapter({...device,deviceId:'d2'}).driver,'execute'),/Verify/);}finally{f.clean();}});
test('mismatched or protected screens never receive replay input',async()=>{for(const screen of [obs('wrong'),{...obs('a'),protectedScreen:true}]){const f=fixture();try{const v=draft(f.store);let calls=0;const r=await replayTeaching(f.store,v.id,{authorize(){},async observe(){return screen;},async execute(){calls++;}},'verify');assert.equal(r.status,'NEEDS_HUMAN');assert.equal(calls,0);}finally{f.clean();}}});
test('uncertain failed input is checkpointed and not resent; restart pauses unfinished runs',async()=>{const f=fixture();try{const v=draft(f.store);let calls=0;const r=await replayTeaching(f.store,v.id,{authorize(){},async observe(){return obs('a');},async execute(){calls++;throw Error('Connection lost after send');}},'verify');assert.equal(r.status,'NEEDS_HUMAN');assert.equal(r.pendingStep,0);assert.equal(calls,1);f.store.beginRun(v,device,'verify');const reloaded=new TeachingStore(f.path);assert(reloaded.list().runs.every(r=>r.status==='NEEDS_HUMAN'));assert.equal(reloaded.get(v.id).status,'DRAFT');}finally{f.clean();}});
test('permission revocation is checked again before executing',async()=>{const f=fixture();try{const v=draft(f.store);let auth=0,calls=0;const r=await replayTeaching(f.store,v.id,{authorize(){if(++auth>=3)throw Error('Session ended');},async observe(){return obs('a');},async execute(){calls++;}},'verify');assert.equal(r.status,'NEEDS_HUMAN');assert.equal(calls,0);}finally{f.clean();}});
test('drafts and Human Gate steps cannot become verified',async()=>{const f=fixture();try{const v=draft(f.store,device,true);const a=adapter();assert.equal((await replayTeaching(f.store,v.id,a.driver,'verify')).status,'NEEDS_HUMAN');assert.equal(a.calls(),0);assert.equal(f.store.get(v.id).status,'DRAFT');}finally{f.clean();}});
test('URL parameter rejects credentials, sensitive query, non-HTTPS and host substitution',()=>{assert.equal(safeUrl('https://example.com/row/2','example.com'),'https://example.com/row/2');for(const url of ['http://example.com','https://user:pass@example.com','https://example.com?token=x','https://evil.example','https://example.com/#secret'])assert.throws(()=>safeUrl(url,'example.com'));});
test('recordings do not serialize raw URL or typed credentials',()=>{const before=obs('a'),after=obs('b');const typed=demonstratedStep({action:'text',text:'TOP_SECRET'},before,after);const opened=demonstratedStep({action:'open-url',url:'https://example.com/private?id=123'},before,after);assert(typed.gate);assert(!JSON.stringify([typed,opened]).includes('TOP_SECRET'));assert(!JSON.stringify(opened).includes('private'));assert.equal(opened.action.kind,'url');});
function xml(label='Next',password='false'){return `<hierarchy><node package="com.example.app" resource-id="com.example.app:id/next" class="Button" text="${label}" bounds="[0,0][100,100]" clickable="true" enabled="true" password="${password}"/></hierarchy>`;}
test('semantic recording identifies unique navigation target and blocks purchases/password screens',()=>{const o=observeAndroidUi(xml(),device);const step=demonstratedStep({action:'tap',x:50,y:50},o,o);assert.equal(step.action.kind,'tap');assert.equal(step.gate,false);assert.equal(step.contextKey,profileKey(device));for(const label of ['購入','Delete','Unknown button']){const o=observeAndroidUi(xml(label),device);assert(demonstratedStep({action:'tap',x:50,y:50},o,o).gate);}assert(observeAndroidUi(xml('Next','true'),device).protectedScreen);const dup=xml().replace('</hierarchy>',xml().replace(/<\/?hierarchy>/g,'')+'</hierarchy>');assert.equal(observeAndroidUi(dup,device).targets.length,0);});
test('invalid observations/storage fail closed instead of resetting evidence',()=>{assert.throws(()=>observeAndroidUi('<hierarchy/>',device));const f=fixture();try{writeFileSync(f.path,'{bad');assert.throws(()=>new TeachingStore(f.path));}finally{f.clean();}});
test('re-recording creates a distinct unverified variant and active device recordings cannot overlap',()=>{const f=fixture();try{const first=f.store.start({goal:'work',scope:'device',profile:device,sessionId:'a'});assert.throws(()=>f.store.start({goal:'work',scope:'device',profile:device,sessionId:'b'}));f.store.cancel(first.id);const second=f.store.start({goal:'work',scope:'device',profile:device,sessionId:'b'});assert.notEqual(first.id,second.id);assert.equal(second.verifiedRunId,undefined);}finally{f.clean();}});
