import assert from "node:assert/strict";
import test from "node:test";
import { FREE_PLANNER_DELEGATE_REASON } from "../src/orchestrator/dashboard-command-routing.ts";
import { FREE_PLANNER_MODEL, UnifiedPlanningClient } from "../src/orchestrator/unified-planning-client.ts";

const goal = {
  title: "Dashboard task",
  description: "Apply the requested bounded UI change",
  successCriteria: ["tests pass"],
  constraints: ["no privileged changes"],
};

const context = [{
  source: "repository.workspace",
  summary: "one bounded file",
  data: { files: [{ path: "src/example.ts", content: "export const value = 1;\n" }] },
}];

function envelope() {
  return JSON.stringify({
    source: "chat",
    command: "この値を2に変更して完成させて",
    plan: {
      kind: "inspect",
      description: "この値を2に変更して完成させて",
      reason: FREE_PLANNER_DELEGATE_REASON,
    },
  });
}

test("dashboard delegated plan uses the allowlisted Cloudflare free model", async () => {
  let requestUrl = "";
  let requestBody: Record<string, unknown> | null = null;
  const fetchImpl: typeof fetch = async (input, init) => {
    requestUrl = String(input);
    requestBody = JSON.parse(String(init?.body ?? "{}")) as Record<string, unknown>;
    return new Response(JSON.stringify({
      success: true,
      choices: [{
        message: {
          content: JSON.stringify({
            kind: "propose_pr",
            description: "Update bounded example value",
            title: "fix: update example value",
            body: "Generated by the free bounded planner",
            files: [{ path: "src/example.ts", content: "export const value = 2;\n" }],
          }),
        },
      }],
    }), { status: 200, headers: { "content-type": "application/json" } });
  };

  const client = new UnifiedPlanningClient(envelope(), {
    env: {
      CLOUDFLARE_ACCOUNT_ID: "account-123",
      CLOUDFLARE_WORKERS_AI_TOKEN: "secret-token",
    },
    fetchImpl,
  });
  const plan = await client.plan({ goal, context });

  assert.equal(plan.kind, "propose_pr");
  assert.equal(plan.files?.[0]?.content, "export const value = 2;\n");
  assert.match(requestUrl, /api\.cloudflare\.com\/client\/v4\/accounts\/account-123\/ai\/v1\/chat\/completions/);
  assert.equal(requestBody?.model, FREE_PLANNER_MODEL);
  assert.equal(FREE_PLANNER_MODEL, "@cf/zai-org/glm-4.7-flash");
});

test("free planner fails closed when credentials are absent", async () => {
  const client = new UnifiedPlanningClient(envelope(), { env: {} });
  await assert.rejects(
    () => client.plan({ goal, context }),
    /CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_WORKERS_AI_TOKEN are required/,
  );
});

test("free planner rejects malformed model output instead of executing it", async () => {
  const fetchImpl: typeof fetch = async () => new Response(JSON.stringify({
    success: true,
    choices: [{ message: { content: "not-json" } }],
  }), { status: 200, headers: { "content-type": "application/json" } });

  const client = new UnifiedPlanningClient(envelope(), {
    env: {
      CLOUDFLARE_ACCOUNT_ID: "account-123",
      CLOUDFLARE_WORKERS_AI_TOKEN: "secret-token",
    },
    fetchImpl,
  });
  await assert.rejects(
    () => client.plan({ goal, context }),
    /invalid bounded plan/,
  );
});

test("ordinary explicit plans still bypass the free provider", async () => {
  let called = false;
  const fetchImpl: typeof fetch = async () => {
    called = true;
    throw new Error("should not be called");
  };
  const client = new UnifiedPlanningClient(JSON.stringify({
    source: "chat",
    command: "確認して",
    plan: { kind: "inspect", description: "確認して" },
  }), { env: {}, fetchImpl });

  const plan = await client.plan({ goal, context });
  assert.equal(plan.kind, "inspect");
  assert.equal(called, false);
});
