import type{WorkAction,WorkCapabilityRegistry,WorkResult}from "./work-capability.ts";import{evaluateFactCompletionGate,type FactGateInput}from "./fact-completion-gate.ts";import type{WorkRunState,WorkRunStore}from "./work-run-state.ts";
export interface PlannedWorkJob{id:string;action:WorkAction;verify?:(result:WorkResult)=>Promise<{ok:boolean;evidenceRef?:string;reason?:string}>;recover?:(input:{action:WorkAction;result:WorkResult;reason:string;attempt:number})=>Promise<WorkAction|null>;}
export interface WorkPlan{jobs:PlannedWorkJob[];factGate?:FactGateInput;}
export class WorkDispatcher{private readonly registry:WorkCapabilityRegistry;private readonly runs:WorkRunStore;constructor(registry:WorkCapabilityRegistry,runs:WorkRunStore){this.registry=registry;this.runs=runs}
async execute(goalId:string,plan:WorkPlan):Promise<WorkRunState>{const now=()=>new Date().toISOString();let state:WorkRunState={runId:`run-${goalId}`,goalId,phase:"RUNNING",currentWork:null,completedJobs:0,totalJobs:plan.jobs.length,recoveryCount:0,blockers:[],nextAction:plan.jobs[0]?.id??null,evidenceRefs:[],createdAt:now(),updatedAt:now()};await this.runs.put(state);
for(const job of plan.jobs){let action=job.action;let attempt=0;for(;;){const cap=this.registry.get(action.capability);if(!cap||!(await cap.available()))return this.block(state,job.id,`capability_unavailable:${action.capability}`,now);state={...state,phase:"RUNNING",currentWork:job.id,nextAction:job.id,updatedAt:now()};await this.runs.put(state);const result=await cap.execute(action);state={...state,evidenceRefs:[...state.evidenceRefs,...result.evidence.flatMap(e=>e.ref?[e.ref]:[])],updatedAt:now()};if(!result.ok)return this.block(state,job.id,result.error??`execution_failed:${job.id}`,now);
if(job.verify){state={...state,phase:"VERIFYING",updatedAt:now()};await this.runs.put(state);const verified=await job.verify(result);if(verified.evidenceRef)state={...state,evidenceRefs:[...state.evidenceRefs,verified.evidenceRef]};if(!verified.ok){attempt+=1;if(!job.recover)return this.block(state,job.id,verified.reason??"verification_failed",now);state={...state,phase:"RECOVERING",recoveryCount:state.recoveryCount+1,nextAction:`recover:${job.id}`,updatedAt:now()};await this.runs.put(state);const next=await job.recover({action,result,reason:verified.reason??"verification_failed",attempt});if(!next||attempt>=3)return this.block(state,job.id,verified.reason??"recovery_exhausted",now);action=next;continue;}}
state={...state,phase:"RUNNING",completedJobs:state.completedJobs+1,nextAction:null,updatedAt:now()};await this.runs.put(state);break;}}
if(plan.factGate){state={...state,phase:"VERIFYING",currentWork:"fact-verification",updatedAt:now()};await this.runs.put(state);const facts=evaluateFactCompletionGate(plan.factGate);if(!facts.passed)return this.block(state,"fact-verification",`fact_gate_blocked:${facts.blockedClaims.join(",")}`,now);}
state={...state,phase:"COMPLETED",currentWork:null,nextAction:null,updatedAt:now()};await this.runs.put(state);return state}
private async block(state:WorkRunState,jobId:string,reason:string,now:()=>string){const blocked={...state,phase:"BLOCKED" as const,currentWork:jobId,blockers:[reason],nextAction:null,updatedAt:now()};await this.runs.put(blocked);return blocked}}
